// src/app/legal/page.tsx
'use client';

import React from 'react';
import { Section } from '@/components/ScrollTypography';

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden pt-24 font-pt-sans">
      <div className="container mx-auto px-4 py-16">
        <Section className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-light text-foreground font-playfair">Legal Disclaimer</h1>
            <p className="text-sm text-muted-foreground mt-2">Effective Date: November 2025</p>
          </div>

          <div className="prose prose-invert max-w-none prose-p:text-muted-foreground prose-headings:text-foreground prose-headings:font-light prose-headings:border-b prose-headings:border-border prose-headings:pb-2">
            
            <h2>1. For Research & Experimental Purposes Only</h2>
            <p>The Go-One Autonomous AI Notebook, its simulations, and all AI-generated content (collectively, the “Platform”) are provided for research, educational, and experimental purposes only. The outputs of the AI are generated by a probabilistic model and should not be considered factual, complete, or accurate.</p>

            <h2>2. No Professional Advice</h2>
            <p>The content and outputs generated by the Platform do not constitute professional advice of any kind, including but not to legal, financial, medical, or technical advice. You should not rely on any information from the Platform as a substitute for consultation with qualified professionals.</p>

            <h2>3. Assumption of Risk</h2>
            <p>You assume full responsibility for your use of the Platform. Any actions you take based on the AI-generated outputs, simulations, or content are taken at your own risk. </p>

            <h2>4. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, the creators and any affiliates, contributors, or associated parties disclaim all liability for any loss, damage, or harm—direct or indirect—arising from your use of, or inability to use, the Platform. This includes any misinterpretation of content, reliance on AI-generated outputs, or interaction with the simulations.</p>
          </div>
        </Section>
      </div>
    </div>
  );
}
