// src/components/notebooks/AudioOverview.tsx
"use client";

import { motion } from 'framer-motion';
import { Play, Pause, Rewind, FastForward, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function AudioOverview() {
    AudioOverview.displayName = 'AudioOverview';
    const isLoading = false; // Placeholder state
    const isPlaying = false; // Placeholder state

    return (
        <div className="max-w-3xl mx-auto px-6 py-12">
            <div className="relative border-t border-white/10 pt-10">
                <div className="relative w-full rounded-lg bg-neutral-900 border border-white/10 p-8 flex flex-col items-center justify-center space-y-6">
                    <p className="text-sm text-neutral-400">AI-Generated Audio Overview</p>
                    
                    <div className="relative h-24 w-24">
                         <motion.div
                            className="absolute inset-0 rounded-full border-2 border-green-400/30"
                            animate={{
                                scale: isPlaying ? [1, 1.1, 1] : 1,
                                opacity: isPlaying ? [0.5, 0.8, 0.5] : 0.2
                            }}
                            transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                        />
                         <motion.div
                            className="absolute inset-2 rounded-full border-2 border-green-400/50"
                             animate={{
                                scale: isPlaying ? [1, 1.05, 1] : 1,
                                opacity: isPlaying ? [0.7, 1, 0.7] : 0.4
                            }}
                            transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                        />
                    </div>

                    <p className="text-neutral-500 text-sm">01:23 / 05:41</p>

                    <div className="flex items-center space-x-4">
                        <Button variant="ghost" size="icon" disabled={isLoading}>
                            <Rewind />
                        </Button>
                        <Button variant="outline" size="icon" className="w-16 h-16 rounded-full" disabled={isLoading}>
                            {isLoading ? <Loader2 className="animate-spin" /> : isPlaying ? <Pause size={24} /> : <Play size={24} className="ml-1" />}
                        </Button>
                        <Button variant="ghost" size="icon" disabled={isLoading}>
                            <FastForward />
                        </Button>
                    </div>
                     <p className="text-xs text-neutral-600 pt-4">This audio is generated by an AI based on the notebook's core concepts.</p>
                </div>
            </div>
        </div>
    );
}
