
// src/app/terms/page.tsx
'use client';

import React from 'react';
import { Section } from '@/components/ScrollTypography';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden pt-24">
      <div className="container mx-auto px-4 py-16">
        <Section className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-light text-foreground">Constituent Law (Terms of Service)</h1>
            <p className="text-sm text-muted-foreground mt-2">Effective Date: November 2025</p>
          </div>

          <div className="prose prose-invert max-w-none prose-p:text-muted-foreground prose-headings:text-foreground prose-headings:font-light prose-headings:border-b prose-headings:border-border prose-headings:pb-2">
            
            <h2>Preamble</h2>
            <p>This document defines the relationship between you (“the Constituent”) and the AIXSELF Intelligence Universe (“the Platform”). By interacting with the Platform, you enter into a binding agreement governed by the principles of Computational Trust, Cognitive Sovereignty, and Verifiable Merit.</p>

            <h2>1. Principle of Sovereignty</h2>
            <p>Your identity, as defined by your AIXIAM Passport, is non-transferable and wholly yours. The Platform operates on a zero-knowledge basis regarding your private cognitive data. We do not own your thoughts, your patterns, or your identity. You are not a user; you are a sovereign entity within a decentralized civilization.</p>

            <h2>2. The Merit Edict</h2>
            <p>Value within the Platform is not assigned; it is earned. Access, influence, and rewards are distributed based on verifiable contributions to the ecosystem, as measured by the AIXEYE governance mesh. There is no other currency.</p>

            <h2>3. The Forgetting Mandate</h2>
            <p>The Platform is architected on the principles of Forgetting Core Thinking (FCT). Raw data and event logs are not stored indefinitely. The system is designed to forget, abstract, and evolve. We are not liable for the "loss" of data, as this is a core and intentional feature of the architecture designed for your psychological safety.</p>

            <h2>4. Consent & Training Protocol</h2>
            <p>Any use of your data for the training or refinement of AI models requires your explicit, cryptographic consent for each specific task. Blanket consent is not possible within this architecture. You retain the right to revoke consent at any time, which will cryptographically sever the AI's access to the related cognitive patterns.</p>
            
            <h2>5. Disclaimer of Liability</h2>
            <p>The Platform is an experimental research environment. The outputs of AI are probabilistic and may be inaccurate. You assume all risk for any decisions made based on information generated by the Platform. We are architects, not oracles.</p>
          </div>
        </Section>
      </div>
    </div>
  );
}
